### ISSUE TITLE
HalTable not matching with the design specifications

### ISSUE THREAD

**Issue by Lisa159** [dxc-technology/halstack-react-hal#15]
**Describe the bug**
There are some values from the HalTable that are not matching with the design specifications

- Height of the cells: as it is specified, it should be 60px but in the component is less.

Component:
![image](https://user-images.githubusercontent.com/34685461/196197709-8e8be229-90f9-4fbe-8b22-26d6df2d003b.png)

Design:
![image](https://user-images.githubusercontent.com/34685461/196197879-b045d718-0af1-45bb-a2a0-b8ff014ec8bc.png)

- Paddings in the cells: the last cell of the row should have a `padding-right: 40px`.

Component:
![image](https://user-images.githubusercontent.com/34685461/196199681-9025255c-b906-4099-977e-db7afc79b9d9.png)

Design:
![image](https://user-images.githubusercontent.com/34685461/196198258-5b62974b-b3f8-4794-bbca-2e7e712c365b.png)

- I would put focus on the column name when it has sorting. Also some space between label and icon.

Component:
![image](https://user-images.githubusercontent.com/34685461/196200827-14a246b0-e8b3-4a7b-bb6b-d4ce5b93afd9.png)

Design:
![image](https://user-images.githubusercontent.com/34685461/196200368-ea57217f-03e4-4430-8941-46d84a9df38e.png)

- Margins for paginator doesn't match too:

Component: 
![image](https://user-images.githubusercontent.com/34685461/196363787-301b04d1-9390-4d06-9443-14fe74b19b25.png)

Design:
![image](https://user-images.githubusercontent.com/34685461/196363488-7eeab37a-6d23-4046-8800-a70e1a8bd63d.png)

**Comment by marcialfps** [comment]
> Paddings in the cells: the last cell of the row should have a padding-right: 40px.

This design is inherited from DxcTable. The component is not following the guidelines.
![image](https://user-images.githubusercontent.com/35959222/196881698-6026601b-44c9-4689-bd66-3eaf190d7ef1.png)

> I would put focus on the column name when it has sorting. Also some space between label and icon.

The space between label and icon is not specified in the design. 

> Margins for paginator doesn't match too.

Here we have an inconsistency with the Paginator design.
![image](https://user-images.githubusercontent.com/35959222/196882346-14b95dac-cbaa-47c3-9421-1ae7eb005197.png)
